gateway:
  server:
    address: 0.0.0.0
    port: 9090

  services:
    mailagent:
      address: mailagent-flask-app"
      port: 8008

    authservice:
      address: auth-flask-app
      port: 8090

    dbmanager:
      address: dbmanager-flask-app
      port: 8000

  logging:
    level: debug
    filename: log.txt


