global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'my-web-app'
    static_configs:
      # - targets: ['gateway-cpp-app:9999']
      - targets: ['mailagent-flask-app:8008']
      # - targets: ['dbmanager-flask-app:8000']
      # - targets: ['dbmanager-flask-app:8000']
      # - targets: ['rabbitmq:5672']
